import {Inter} from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import { Toaster } from "sonner";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({
  subsets: ["latin"],
});
export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
       className={`${inter.className} bg-white text-slate-900 antialiased`}
      >
        <Provider>
        {children}
        </Provider>
        <Toaster />
        
      </body>
    </html>
    </ClerkProvider>
  );
}
